export const FETCH_WAREHOUSES_REQUEST = "FETCH_WAREHOUSES_REQUEST";
export const FETCH_WAREHOUSES_SUCCESS = "FETCH_WAREHOUSES_SUCCESS";
export const FETCH_WAREHOUSES_FAILURE = "FETCH_WAREHOUSES_FAILURE";
export const FILTER_WAREHOUSES = "FILTER_WAREHOUSES";
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
